name: Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.3.1
      - run: deno run --allow-write --allow-net scripts/fetch_registered_funds.ts
      - run: cd pdfs && ./generate.sh
      - run: deno test --allow-read --allow-net src/{,**/}*_test.ts
  publish:
    needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.3.1
      - run: deno run --allow-write --allow-net scripts/fetch_registered_funds.ts
      - run: cd pdfs && ./generate.sh
      - run: deno publish --allow-dirty