name: Tests
on:
  schedule:
    - cron: "30 1 * * *"
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v2.3.1
      - run: deno run --allow-write --allow-net --allow-import scripts/fetch_registered_funds.ts
      - run: cd pdfs && ./generate.sh
      - run: deno test --allow-read --allow-net src/{,**/}*_test.ts
