name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '30 1 * * *'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v1
        with:
          deno-version: v1.41.3
      - run: deno run --allow-write --allow-net scripts/fetch_registered_funds.ts
      - run: deno test --allow-read --allow-net src/{,**/}*_test.ts